### ISSUE TITLE
Pre-alpha testers?

### ISSUE THREAD

**Issue by robby4769** [daledesilva/obsidian_ink#1]
Hi - are you open to some pre-alpha testing? I really like the look of this. 

I currently use the handwritten note plugin for handwriting within Obsidian, and Nebo outside of Obsidian. 

I can test with iPad Pro, iPad mini, and various MS Surface devices. 

Let me know!

**Comment by daledesilva** [comment]
There's still a couple of changes I wanna make even before that (critical issues that I'm aware of), but I'll let you know.

In the meantime, did you see this video I put up the other day on it:
[https://www.youtube.com/live/_yFYaBUrlBo?si=31TdyOTy1GovQ1jb](https://www.youtube.com/live/_yFYaBUrlBo?si=31TdyOTy1GovQ1jb)


Thanks for the enthusiasm!

**Comment by robby4769** [comment]
Yes I did - that's why I reached out! Looks great in current state, and exactly like what I'm looking for as a user. 

Depending on what you're looking for, I may be able to contribute as well.

**Comment by daledesilva** [comment]
Oh, great!
The next 4 items on the roadmap up to "Alpha Release" are pretty important or small, so I still wanna get those done first.
For instance, one of the things is to convert the embed format which will mean updating all existing embeds. At the moment I can do that manually because it's just me using it - So that update needs to happen before anyone else starts.

Thanks so much for the interest!

**Comment by darkwolfgar** [comment]
Also interested in testing! Seeing your video the other week made me just want to start using it now as it already looks very usable in its current state.

**Comment by KuiyueRO** [comment]
+++++++++++++++++ 

XD

**Comment by daledesilva** [comment]
Hey all.
I've just submitted the alpha to obsidian. It might be a week or so before it's available through there but you can install it now through the Brat plugin (instructions in the Readme).

I'll create a video stepping through the plug-in tomorrow :) 

Thanks for wanting to try it out!

**Comment by robby4769** [comment]
I get an error in BRAT that your repo is missing main.js.

excited to try it!!

**Comment by daledesilva** [comment]
I've tried it on 2 devices don't get that error. You may have pasted in the wrong url.
Use this:
```
https://github.com/daledesilva/obsidian_ink
```

**Comment by robby4769** [comment]
Thanks, I got it installed! Early experience very positive. Will post additional feedback under separate issues.
