### ISSUE TITLE
Mobile toolbar icons

### ISSUE THREAD

**Issue by petertung** [daledesilva/obsidian_ink#101]
**What's your idea?**
Adding mobile toolbar icons.

**Why? How would it help you (or others)?**
Right now they're (i assume default) question mark icons for all the ink commands.  So in the toolbar, can't differentiate the icon for adding a new writing, vs adding new drawing.

**Any examples or references you think are worth pointing out?**
![Screenshot_20241218-022958](https://github.com/user-attachments/assets/7729ca28-8920-4f3d-99d4-1c70cda5a8f2)

**Anything else?**
I love your plugin and tell lots of people to try it out! Thank you!

**Comment by daledesilva** [comment]
Thanks for the comment and for spreading the word!

I put icons in the last update (thought they're temporary till I design them better).

The last update was just if you're using Brat, but I'll release it properly soon :)

**Comment by petertung** [comment]
You da man!
