### ISSUE TITLE
Suggestion: Use TLDraw as the drawing backend

### ISSUE THREAD

**Issue by Azeirah** [daledesilva/obsidian_ink#12]
Before I saw your plugin on Reddit, I was working on modifying an existing Obsidian TLDraw plugin to support remote editing (I'll explain it in a second), the prototype works very well. It's based on this plugin: https://github.com/holxsam/tldraw-in-obsidian (my fork is not available anywhere yet, only on my pc)

I think for your use-case, TLDraw makes a lot more sense than building your own drawing application + tools. Why?

1. TLDraw is a drop-in editor
2. The UI is 100% customizable, you can enable and disable whatever tools you want, and restyle them however you want
3. Its data is serializable and exists as JSON
4. A solid user as well as programming community is growing around it
5. Its API as well as its serial format is well documented: https://tldraw.dev/
6. It's built in mind with remote/collaboration and sharing in mind

And to be more convincing, maintenance of cross-platform drawing bugs are not your burden anymore. Want apple pencil pressure support? TLDraw has it! Samsung galaxy S pen? TLDraw has it. JS pointer events? Yep. Microsoft surface pen? Yessire. Wacom drawing tablets? For sure! Any bugs can be redirected towards mainline. Copy paste? Built-in! Images? Built-in!

---

Now a quick explanation of what I'm prototyping:

I often read books, and while reading books I really like to take _written_ notes. I have a laptop as well as a Samsung galaxy note phone. The phone's screen is too small for creative notes whereas the laptop is too cumbersome.

My idea was to add remote editing to any TLDraw surface anywhere within Obsidian, so you get a link to a surface and by opening it on my phone, I get a mirror of the TLDraw surface on my phone. So I get a big screen with a small notepad I can draw on! It's like using my phone as a drawing tablet.

I'm going to continue working on it

**Comment by daledesilva** [comment]
Ha ha. Thanks for such a thoughtful reply anyway.
I look forward to hearing about your remote notepad plugin progressing!

I love to take written notes while I read too, but I use my iPad - and I exclusively read on my iPad when I'm reading stuff I'd wanna take notes for. (I purposely bought an eInk reader too because I was finding I was taking more notes than reading, so now all my fiction and fun reading is done on the eReader so that I _can't_ take notes!)
