### ISSUE TITLE
Feature Suggestion: Erase All Option in Ink

### ISSUE THREAD

**Issue by fredjoe7** [daledesilva/obsidian_ink#16]
there are situations where i want to erase all ink on a page quickly and efficiently. To address this need, I suggest adding an "Erase All" option to the Ink plugin.
This option would allow users to erase all ink on a page with a single click, saving them time and effort.

**Comment by fredjoe7** [comment]
Thats a good option to add on its own.

I could set hotkeys to delete and create new embeds quickly if needed  probably using autohotkey in windows. 

Which potentially also functions as erase all..  and in other cases to just delete the embed .

**Comment by daledesilva** [comment]
Covering in #29
