### ISSUE TITLE
Will it work on non-touch laptop screen?

### ISSUE THREAD

**Issue by amatya-aditya** [daledesilva/obsidian_ink#2]
Basically title.

**Comment by daledesilva** [comment]
Yep. You can draw with your mouse or a touchpad if you want.

Btw. I just released the alpha.
You can follow the install instructions in the Readme if you’d like to try
it.

___________________________________
Dale de Silva
twitter: @daledesilva
projects: daledesilva.com

Does your business support a discussion about Australia Day?
Ask me about displaying your support on changeitourselves.com.au
