### ISSUE TITLE
REQUEST: be able to choose name for ink folder

### ISSUE THREAD

**Issue by tenebrisnox** [daledesilva/obsidian_ink#20]
(A really minor request...)

Is it possible in a future release to give users the ability to name the folder where the .writing files are stored?

Also, any plans to automatically delete .writing files when a note containing them is deleted (or give the choice of deleting them)?

**Comment by ichmoimeyo** [comment]
@tenebrisnox 
"ability to name the folder where the .writing files are stored"
hi, in the meantime  you can achieve something similar yourself by **setting: `Default location for new attachments`:**
![Screenshot 2024-04-05 06 43 29](https://github.com/daledesilva/obsidian_ink/assets/33708734/049167f5-cf65-413f-a0e5-f4816b266a39)

e.g. **myInkFolder** as the folder where the .writing files are stored:
```
Default location for new attachments: in the folder specified below: 
Attachment folder path: myInkFolder
```
... your options are:
as above ...
**in the folder specified below:**
... Attachment folder path: **myInkFolder** ... this lets you choose your top level name with **Ink** however still below it.
OR
**same folder as current file** ... it would still be called **Ink** however.

**in subfolder under current folder**  ... it would still be called **Ink** however.

**Comment by JeminiRiver** [comment]
I've forked the repository and added the setting successfully but I'm encountering Build errors on the **main** branch with the _@tldraw:2.0.0-alpha.17_ dependency. I merged my changes onto a local copy of the **release_0.1.2** branch after seeing dependency updates there but I'm getting the same Build errors. Just curious if you're encountering the same build errors atm, @daledesilva?

**Comment by daledesilva** [comment]
@JeminiRiver i only updated those dependencies on that branch last night so can't say confidently, but I don't believe so.

It's possible you merge it between my commits and didn't get all my updates. Maybe try merging again.

Either way, I'll put in an option for defining the folder names in the next release myself if you can wait.

**Comment by YkionArt** [comment]
Along with name, changing location of the Ink folder independently from settings in "Files and links" would be nice too. If I'm not mistaken, the plugin currently uses same folder as "new note" ? Personally I'd like my notes to be in the "new attachments" folder instead, for example.

**Comment by daledesilva** [comment]
This is now implemented. If you want to use it immediately you can install the latest prerelease version (0.2.3) through BRAT.
Or if not using BRAT, you'll need to wait till it becomes the official release.
Thanks for you comments!

**Comment by batrand** [comment]
@daledesilva So we have 2 options, 1 is the root folder, 2 is the Obsidian attachments folder. Can I request a third option, which is to use a path relative to the note? 

What I'm imagining is if I set this setting to "_attachments" for example:
- if my note is in /Folder/Subfolder/Note.md, Ink files will be in /Folder/Subfolder/_attachments/file.writing
- if my note is in /Folder2/Subfolder2/Note2.md,. Ink files will be in /Folder2/Subfolder2/_attachments/file2.writing

My use case is a single vault for all aspects of life, and on my work devices, I only store the work subfolder, so I don't want personal notes and attachments synced there.

**Comment by daledesilva** [comment]
Lol. I knew someone would want this but I didn't think I'd hear back so quickly!
I'm aware of this deficiency, but I decided to limit how much work I put into this ticket to start.

I'm going to jump on some other more high priority things first, but I will create a new issue for this and hopefully implement it sooner rather than later!

Thanks for voicing it @bartrand
