### ISSUE TITLE
[FEATURES REQUEST] ANOTATION on pdf and images

### ISSUE THREAD

**Issue by JE-Amouel** [daledesilva/obsidian_ink#26]
Hello, 
would it be possible to add an option, to import an image or a PDF page, to be able to make annotations? 
Feature description: 
We could have an imported button, after pressing the button, we will have two options,
 - pictures 
 - pdf page 
 
 Picture: 
If we choose image, we could choose an image via the means made available by the platform where obsidian is installed (pc, ios, Android), then the image would be loaded in the Ink editor, and we could write on it to annotate important things, 

PDF page: 
Same as for image, except that, after choosing the pdf, we will also choose the page and we could annotate on it, And for both imports, we keep metadata, which would trace the original file. 

To popularize the functionality a little, it would basically be like having the possibility of having a background image in the Ink editor,

THANKS.

**Comment by daledesilva** [comment]
Thanks for the suggestion.
Unfortunately, this functionality would involve some divergence from the focus of Ink so I'm unlikely to take it in this direction.

However, there's already a plugin called Handwritten Notes that allows annotation of PDFs (I'm not sure about images).
