### ISSUE TITLE
Removing an entire note from the markdown document

### ISSUE THREAD

**Issue by HerrNamenlos123** [daledesilva/obsidian_ink#29]
**What's your idea?**

I just started using this plugin, so sorry if I am overseeing something and it is already possible, but when i create an inline note using my shortcut CTRL+ALT+N, the ink area spawns, but then I don't see a way to remove the note again. I can only delete content in the note, but not remove the entire note from the markdown document.

The only way I was able to remove it was by fiddling around to get to the source-mode so i saw the text that imports the note, and deleting the entire source text.

To be consistent with the rest of Obsidian, I would expect that I can select the entire note by dragging the mouse over it (or hitting backspace below it) and then delete it using DEL or backspace.

The significantly easier way would probably be to simply add a button called "Delete Note". (and maybe a popup that asks if you just want to delete the reference or the entire note forever)

**Why? How would it help you (or others)?**

I think it would make the plugin more complete as it should always be possible to delete notes after creating them.

**Any examples or references you think are worth pointing out?**

-

**Anything else?**

Thank you so much for this amazing plugin! I was looking for exactly this! I am glad I asked Reddit and found your Plugin, it's perfect for me.

**Comment by daledesilva** [comment]
Thanks @HerrNamenlos123 
Both the button to delete and the ability to backspace delete are things I'm intending to implement, however, I'm still trying to figure out how to do the backspace to delete. Do you have an example plugin that does it? All plugins I see work like ink does currently.

I know the native tables work with backspace, but I don't think I can look at their code to check.

**Comment by daledesilva** [comment]
This was implemented in 0.2.4
Thanks for requesting :)
