### ISSUE TITLE
While using a tablet stylus, writing will open the left or right sidebars if the pen is swyped in either direction.

### ISSUE THREAD

**Issue by starlogic** [daledesilva/obsidian_ink#30]
The title captures its essence; when attempting to write with my Galaxy 8 tablet, and I write horizontally to the left, the right sidebar will open, and the right sidebar will open when writing in the opposite direction.

https://github.com/daledesilva/obsidian_ink/assets/38538697/b7b3ccba-60cd-47fa-b6c7-72bd03f3e85c

- **Device & OS**: Samsung galaxy s8+ tablet
- **Plugin version**: 0.1.181
- **Obsidian version**: 1.5.12

**Comment by daledesilva** [comment]
Thanks for the video @starlogic !
I thought I'd at least partially fixed this, but I'm still seeing it on my iPad as well.

I'll look into it and get it working right 👍🏽

**Comment by daledesilva** [comment]
@starlogic 
I'm working on this now. On my iPad I can reproduce it but only with the second embed on the page.
The first embed on the page from the top successfully prevents the panels opening, but when more embeds are present the others don't.

Can I confirm that you don't have any more embeds in the page above what you've shown?
Just want to be sure that if I fix the bug I'm seeing it will likely fix the bug you're experiencing.

**Comment by MrComputron** [comment]
I have same experience on S23 Ultra. Pen stroke starts left or right pulls out side bars, if stroke starts with vertical motion and continues to side motion there is no issue.

**Comment by starlogic** [comment]
> @starlogic I'm working on this now. On my iPad I can reproduce it but only with the second embed on the page. The first embed on the page from the top successfully prevents the panels opening, but when more embeds are present the others don't.
> 
> Can I confirm that you don't have any more embeds in the page above what you've shown? Just want to be sure that if I fix the bug I'm seeing it will likely fix the bug you're experiencing.

I've just confirmed that this is occurring only after making a third instance of ink and apparently every instance after.

While probably superfluous, the behavior is the same on my Galaxy S22 Ultra.

**Comment by MrComputron** [comment]
I also just tested in a new note. From the 4th ink onwards the side panels started opening.
Tested it with both drawing and handwriting and the issue only happened with drawing.
