### ISSUE TITLE
Dark mode inversion

### ISSUE THREAD

**Issue by bjornfiles** [daledesilva/obsidian_ink#38]
Color inversion when dark mode is active in Obsidian, so a drawing or handwriting section matches the rest of an Obsidian note when dark mode is active in Obsidian..

Nice plugin!

**Comment by daledesilva** [comment]
Colour changes now happen automatically without needing to re-edit. You can try this out in version 0.1.192 by installing through BRAT.

Lemme know if you have any issues.

**Comment by osha-git** [comment]
Hi! 

Thanks for this great plugin!

I'm having an issue where the pen colour doesn't change when I switch from dark to light mode (or vice versa) on my iPad. It works in edit mode, but not in read mode. I am using version 0.4.0.

**Comment by daledesilva** [comment]
Thanks for reporting. This is fixed already but not in versions 0.4.0.
Since you're already on a beta, upgrade to 0.5.0, I can't remember if the fix is in that but if it isn't it will be in the next one.
