### ISSUE TITLE
Pasting images inside the embedded handwriting canvas

### ISSUE THREAD

**Issue by mistune** [daledesilva/obsidian_ink#4]

**Comment by daledesilva** [comment]
Thanks for dropping a message.

Pasting an image into the embed isn't something this plugin will support, however, it's possible that I've forgotten to disable it.

Could you describe what you've noticed further?

**Comment by mistune** [comment]
Hello, I just re-read the page readme file and noticed that the focus of this plugin is for handwriting only. I can do with just pasting outside of the drawing. Great work.
