### ISSUE TITLE
"Create New Ink" Option

### ISSUE THREAD

**Issue by MrComputron** [daledesilva/obsidian_ink#40]
**What's your idea?**
Option to "create new drawing" instead of "insert new drawing"

**Why? How would it help you (or others)?**
Sometimes it is cumbersome to sketch within the note (due to keyboard popping up due to inadvertent touch inputs, line numbers, etc.)
Having the option to create new drawing and open it for editing would present a minimal sketch interface without distraction or interference by other ui elements.

**Any examples or references you think are worth pointing out?**

**Anything else?**

**Comment by daledesilva** [comment]
Pretty sure you're on the newest version with the pretty buttons...

After you insert a drawing, click on the 3 dots button to the right of the lock button.
Then click "open drawing".

I believe this is what you want.
In this view you can also zoom in and out.

Just click back to then go back to your markdown file.

Lemme know how you go.
