### ISSUE TITLE
image syncing between devices

### ISSUE THREAD

**Issue by leoxiang66** [daledesilva/obsidian_ink#47]
Hi,

I noticed that the drawings are stored locally on pads so that the on desktop it cannot render the drawing because image file not found.

So could you maybe consider to store the image files to some cloud so that it can be shared between devices.

Thanks.

**Comment by daledesilva** [comment]
The drawings are stored in your Obsidian vault like any other file. If you sync your vault to another device then they will go with it.

However, I believe Obsidian sync requires you to turn on "Sync all other types" in the Obsidian sync settings.

**Comment by leoxiang66** [comment]
> The drawings are stored in your Obsidian vault like any other file. If you sync your vault to another device then they will go with it.
> 
> However, I believe Obsidian sync requires you to turn on "Sync all other types" in the Obsidian sync settings.

Thanks, I fixed it.
