### ISSUE TITLE
"Added a welcome tutorial." - Not showing correctly in LIGHT mode

### ISSUE THREAD

**Issue by ichmoimeyo** [daledesilva/obsidian_ink#49]
**Describe the bug**
"... welcome tutorial." - Not showing correctly in LIGHT mode

**screenshots**
Dark mode - showing correctly:
![ink_dark](https://github.com/daledesilva/obsidian_ink/assets/33708734/c0903bb2-2945-4d26-b66a-6a0ca700e243)
Light mode - not showing correctly:
![ink_light](https://github.com/daledesilva/obsidian_ink/assets/33708734/d1b4c9bb-653c-42f1-8f69-0c926360f68b)

**Desktop (please complete the following information):**
- **Device & OS**: 
- Acer Chromebook 317, Linux-Crostini
- Moto g Stylus, Android

- **Plugin version**: 0.2.1
- **Obsidian version**: v1.5.12

**Additional context**
Not that important, as it doesn't interfere with actually using the plugin, but I thought I might as well point it out.
Also ... how does one run the "Welcome tutorial" again without having to delete the data.json file?

**Comment by daledesilva** [comment]
Thank you. I forgot to test that. I've fixed it now and uploaded 0.2.2.
You can rewatch the tips in the settings (Setup tips and tutorial section)
