### ISSUE TITLE
Embeds are not centered

### ISSUE THREAD

**Issue by tobias0409** [daledesilva/obsidian_ink#52]
**Describe the bug**
The embeds are sometimes not centered. Most of the time reloading Obsidian fixes the error.

**Video or screenshots**
![grafik](https://github.com/daledesilva/obsidian_ink/assets/57797397/31882111-295e-4d75-b16e-1b447cbe0f42)

**To Reproduce**
As far as I can see it: I happens when I enter the code block and when I leave the code block again, it slides to the left.
Video link where I show the error: https://jumpshare.com/s/MCsqyEfVxQ4OveM35WFz

**Expected behavior**

**Desktop (please complete the following information):**
- **Device & OS**: Custom PC / Windows 10
- **Plugin version**: 0.2.2
- **Obsidian version**: 1.5.12

**Additional context**
Already tried reinstall ink.

**Comment by daledesilva** [comment]
Thanks. What theme are you using?

Please try a couple of other themes and see if it persists.

**Comment by tobias0409** [comment]
I use the *Minimal* theme. It is the most downloaded theme and therefore sits right next to the default theme.

**Comment by daledesilva** [comment]
Thanks. I'll install the minimal theme and see what's going on

**Comment by FelipeFcosta** [comment]
I also use the Minimal theme and was able to fix it by just changing 

https://github.com/daledesilva/obsidian_ink/blob/45db64283b2ee3ee020a4f1500fa5d8a9fafc126/src/utils/embed.ts#L84-L85

to

```
	style += `; margin-left: auto !important`;
	style += `; margin-right: auto !important`;
```

It might have some unintended consequences, but it works for me.

**Comment by daledesilva** [comment]
Interesting. I'm sure I would have tried that first and found it wasn't working for some reason.

But if that works, I'll put it back in and do some tests with other themes.

Thanks

**Comment by tompaulick** [comment]
I can attest this is also a problem on Android

![Screenshot_20240702_124243_Obsidian](https://github.com/daledesilva/obsidian_ink/assets/54782464/af66ca93-e26d-41e4-8f8c-80d89b35fab0)

**Comment by scosant** [comment]
ran into the same issue as well. also using the minimal theme, and suggestion above to modify `margin-left` and `margin-right` also re-centered the ink embed.

**Comment by jaketae** [comment]
Hi, I'm also facing this issue. I'm new to Obsidian and am not familiar with how to apply the changes suggested above. Where / how can I access the source code for the Ink plugin to edit `embed.ts`?

**Comment by daledesilva** [comment]
I've fixed this... it will be in the next update
