### ISSUE TITLE
Reading 'getMarkdownFiles'

### ISSUE THREAD

**Issue by LuciaCorreaDaSilva** [daledesilva/obsidian_ink#6]
Error when generating tasks from files: TypeError: Cannot read properties of undefined (reading 'getMarkdownFiles')

This error appears when I use Slash Commander to call the plugin on Windows. This prevents me from creating any new notes until I restart the Obsidian, remove ink, and erase any ink's writing file.

**Comment by daledesilva** [comment]
Thanks for reporting! Sorry that's happening.

Is it only when using in combination with slash commander? Or is it also when running the ink commands without slash commander?

**Comment by daledesilva** [comment]
Also, I assume this error is listed in the devtools console?
Does it mention a filename or line number?

If you can take a screenshot that would be really helpful :)

**Comment by daledesilva** [comment]
Closing this... as it should be fixed in the newer versions. Let me know if there's still any related issue.
