### ISSUE TITLE
Will it be able to use it with an external device like the RM2? 

### ISSUE THREAD

**Issue by der-lu** [daledesilva/obsidian_ink#8]

**Comment by daledesilva** [comment]
Should run on anything that runs Obsidian. It only exists as a plug-in for that.

**Comment by Azeirah** [comment]
The remarkable doesn't support third party plugins nor obsidian, so it's unlikely.

It's possible that someone creates an application for the remarkable though, but that requires advanced modifications to the device.

**Comment by daledesilva** [comment]
Yeah, unfortunately it's only for Obsidians. Thanks for your interest!
