### ISSUE TITLE
Maybe add "Export svg" button?

### ISSUE THREAD

**Issue by Lelo147** [daledesilva/obsidian_ink#82]
**What?**
It would be great to additionally store the drawing/writings as .svg file in the Ink folder in order to future-proove the notes to still have value even if Obsidian should maybe not exist anymore at some day.

**How**
I think it would be nice to have the possibility in the plugin settings, to choose whether an additional .svg should be stored (and updated) or whether it can be generated by a button for each writing/drawing individually.

**Anything else?**
Very nice plugin by the way, keep up the good work!

**Comment by daledesilva** [comment]
Duplicate of #75
