### ISSUE TITLE
Freehand selection

### ISSUE THREAD

**Issue by DoS007** [daledesilva/obsidian_ink#88]
**What's your idea?**
Select not by rectangle but freehand.

**Why? How would it help you (or others)?**
Sometimes a rectancle selection isn't sufficient, see constructed example.

**Any examples or references you think are worth pointing out?**
OneNote for Win10:
<img src="https://github.com/user-attachments/assets/fe0bd738-c040-412f-b705-24ad9aa44cd4" width="300">
To always close the selection, the beginning and the end of the the freehand is always connected with a straight line.

**Anything else?**
Thanks for your project. I wouldn't want to miss OneNotes ink feature and at the moment i see no crossplattform (windows, ipad, android) alternatives to OneNote which can mix text and ink (but maybe i just don't know the right ones), but you help make one with your plugin in obsidian.

**Comment by daledesilva** [comment]
Currently, the Tldraw framework this is built on doesn't appear to support this (I would love it as well).
However, I just did some experimentation and testing and found that it does have a feature that might help you here.

If you hold alt (or option on a mac) while the arrow tool is selected, you can scribble over anything you want to select and it will select anything you touch. You can then use shift with that method to add to the selection. Not sure if you can subtract from it in the same way.

I'll definitely keep an eye on this to improve the workflow.
Closing for now
