### ISSUE TITLE
Insert New Block does not show the new block in UI; must insert new and then insert exisitng

### ISSUE THREAD

**Issue by robby4769** [daledesilva/obsidian_ink#9]
Occurs for both handwriting and drawing 

"Insert New..." Creates the block but does not show it in the note. 
Immediately doing "Insert Existing..." shows that the block was created, and selecting it makes it show up in the UI

**Comment by daledesilva** [comment]
Hmm interesting.
Do you mind opening the dev tools (ctrl+shift+I on windows or cmd+shift+I on Mac) and screenshotting any messages you get in the console after trying to create a new block.

**Comment by daledesilva** [comment]
I believe this should be fixed now.
Please update and let me know if there are further issues.

Brat supposedly updates plugins on startup, so try starting Obsidian, give it a minute to update, then close and restart obsidian again. Check that Ink is now 1.15 or higher.

If it hasn't updated that way, you may have to uninstall it through BRAT and the normal plugin area and then install it with BRAT again.

**Comment by daledesilva** [comment]
Closing this... as it should be fixed in the newer versions. Let me know if there's still any related issue.
