### ISSUE TITLE
Wrong file organisation

### ISSUE THREAD

**Issue by SchneiderSam** [daledesilva/obsidian_ink#91]
**Describe the bug**
I have under `Ink -> Customise file organisation` This setup: "Obsidian Attachment folder"
![image](https://github.com/user-attachments/assets/273528cf-1b58-456b-b404-52cd2f1dad2f)

But when i insert a new ink the path is the following:

"Calendar/Notes/Atlas/Utilities/Images/Atlas/Utilities/Drawings/2024.10.25 - 7.38am.drawing

But it should be

Atlas/Utilities/Drawings/2024.10.25 - 7.38am.drawing

Screenshot:
<img width="491" alt="image" src="https://github.com/user-attachments/assets/38ed874a-49e3-4276-a6b6-5e35adff034c">

**Expected behavior**
I would expect, that my Drawings are under:
![image](https://github.com/user-attachments/assets/77e7fbda-3944-4392-b7a0-3db712d05b7f)

My Handwritings under:
![image](https://github.com/user-attachments/assets/ff2ab9e5-b567-4b2e-9ba2-278b93ab2c13)

**Desktop (please complete the following information):**
- **Device & OS**: Windows 11
- **Plugin version**: 0.2.6
- **Obsidian version**: 1.7.4

**Comment by SchneiderSam** [comment]
https://github.com/user-attachments/assets/ad1109e6-b24d-44fc-863b-4807e59785a3

**Comment by daledesilva** [comment]
Oh! Weird.
Were the calendar/notes path folders you already had? Or did ink create those?

Could you show me a screenshot of the obsidian attachment folder setting?

**Comment by SchneiderSam** [comment]
@daledesilva i think there is a bug in core or am i missing something?

https://github.com/user-attachments/assets/9e6a29f8-6e4b-4a8c-8985-6bf3c5e21b93

**Comment by daledesilva** [comment]
Sure looks like it!
Does the folder you're selecting definitely exist? That could be causing it.

Otherwise, yeah, I post about that on the obsidian forums.

I'll look into the other thing as well when I'm back on deck in a few weeks.

**Comment by SchneiderSam** [comment]
> I'll look into the other thing as well when I'm back on deck in a few weeks.

yes, its a bug, they will fix it in 1.7.5 untill then i have to wait 😶

**Comment by daledesilva** [comment]
Hey @SchneiderSam 
How is you travelling with this now? Did any Obsidian updated address any part of it?

**Comment by SchneiderSam** [comment]
> How is you travelling with this now? Did any Obsidian updated address any part of it?

it works now. Thanks
